version: '3.7'

services:

  # apache
  web:
    build: ./.docker/apache
    ports:
      - "81:80"
    volumes:
      - ./:/var/www/html/:ro
      - ./.docker/apache/sites-available:/etc/apache2/sites-available
    depends_on:
      - logstash

  # mail hog
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1026:1025"
      - "8026:8025"

  # elastic
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9201:9200"

  # logstash
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    ports:
      - "5001:5000"
    volumes:
      - ./.docker/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./.docker/logstash/pipeline:/usr/share/logstash/pipeline/
    depends_on:
      - elasticsearch

  # kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    ports:
      - "5602:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

