name: Phpunit Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name : Update composer
      run: make

    - name: phpunit
      id: phpunit
      run: make test

    - name: Discord notify
      if: steps.phpunit > 0
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook_url:
        message: 'PHPUnit Failed ! Great job!'

    - name: Send email
      if: always()
      uses: betterfor/action-sned-mail@main
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.EMAIL_USER }}
        password: ${{ secrets.EMAIL_PWD }}
        subject: ${{ steps.phpunit.outcome == 'success' ? 'Build Success' : 'Build Fail' }}
        body: ${{ steps.phpunit.outcome == 'success' ? 'PHPUnit tests passed successfully.' : 'PHPUnit tests failed!' }}
        to: ${{ secrets.DEST_EMAIL }}
